"""add company_emails table

Revision ID: 8477c1466b70
Revises: 8c23ebd8d935
Create Date: 2026-06-12 02:56:34.520548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8477c1466b70'
down_revision: Union[str, None] = '8c23ebd8d935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sent_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'email', name='uq_company_email')
    )
    with op.batch_alter_table('company_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_emails_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_emails_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_emails_email'))
        batch_op.drop_index(batch_op.f('ix_company_emails_company_id'))

    op.drop_table('company_emails')
    # ### end Alembic commands ###
