"""add subject ab to campaigns

Revision ID: be707cef6260
Revises: f7g8h9i0j1k2
Create Date: 2026-04-26 05:30:58.018754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be707cef6260'
down_revision: Union[str, None] = 'f7g8h9i0j1k2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_email_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_a', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subject_b', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_email_campaigns', schema=None) as batch_op:
        batch_op.drop_column('subject_b')
        batch_op.drop_column('subject_a')

    # ### end Alembic commands ###
