"""add review fields to raw_companies

Revision ID: 32d3781c3b04
Revises: j4k5l6m7n8o9
Create Date: 2026-04-21 16:13:30.989554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d3781c3b04'
down_revision: Union[str, None] = 'j4k5l6m7n8o9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_review', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('review_reason', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_companies', schema=None) as batch_op:
        batch_op.drop_column('review_reason')
        batch_op.drop_column('needs_review')

    # ### end Alembic commands ###
