"""add pipeline status fields to CityRefRow

Revision ID: 66ae407bd723
Revises: 32d3781c3b04
Create Date: 2026-04-21 18:19:28.875136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ae407bd723'
down_revision: Union[str, None] = '32d3781c3b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities_ref', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pipeline_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pipeline_phase', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pipeline_updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cities_ref_pipeline_status'), ['pipeline_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities_ref', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_ref_pipeline_status'))
        batch_op.drop_column('pipeline_updated_at')
        batch_op.drop_column('pipeline_phase')
        batch_op.drop_column('pipeline_status')

    # ### end Alembic commands ###
